#!/usr/bin/env python

confs = [ { 'name':'HIMSST',
            'file':'../../link/data/netCDF/HIMSST/20??/nc_sst.2*',
#            'file':'../../link/data/netCDF/HIMSST/2023/nc_sst.20230101',
            'kind':'mricom-history',
            'undef':999.,},
          { 'name':'MGDSSTnorm',
            'file':'../../link/data/netCDF/MGDSST/norm/nc_sst.2004*',
            'kind':'mricom-history',},
          { 'name':'JPNv2',
            'file':'../../link/data/JPN20-assim/hst_day-jpn/nc_t/20*/nc_t.20*',
#            'file':'../../link/data/JPN20-assim/hst_day-jpn/nc_t/2009/nc_t.20090101',
            'kind':'mricom-history',},
          { 'name':'test',
            'file':'../../link/omipj-data/mricom_user/japan_sea/himsst.2025010*',
            'kind':'mricom-history',},
          { 'name':'MGDSST',
            'file':'../../link/data/netCDF/MGDSST/*/nc_sst.*',
#            'file':'../../link/data/netCDF/MGDSST/2023/nc_sst.20230101',
            'kind':'mricom-history',},
          { 'name':'MOVEJPN',
            'file':'../../link/data/netCDF/JPN/202?/nc_t.202*',
#            'file':'../../link/data/netCDF/JPN/2023/nc_t.20230101',
#            'file':'../../link/data/netCDF/JPN/month/nc_t.202101',
            'kind':'mricom-history',},]
